export type Finger =
  | "l-pinky"
  | "l-ring"
  | "l-middle"
  | "l-index"
  | "r-index"
  | "r-middle"
  | "r-ring"
  | "r-pinky"
  | "thumb";

export const englishFingerLabels: Record<Finger, string> = {
  "l-pinky": "Left Pinky",
  "l-ring": "Left Ring",
  "l-middle": "Left Middle",
  "l-index": "Left Index",
  "r-index": "Right Index",
  "r-middle": "Right Middle",
  "r-ring": "Right Ring",
  "r-pinky": "Right Pinky",
  thumb: "Thumb",
};

export const fingerColors: Record<Finger, string> = {
  "l-pinky": "oklch(0.62 0.19 300)",
  "l-ring": "oklch(0.62 0.18 265)",
  "l-middle": "oklch(0.65 0.16 232)",
  "l-index": "oklch(0.66 0.14 200)",
  "r-index": "oklch(0.66 0.15 165)",
  "r-middle": "oklch(0.68 0.16 140)",
  "r-ring": "oklch(0.72 0.15 95)",
  "r-pinky": "oklch(0.7 0.17 55)",
  thumb: "oklch(0.6 0.05 258)",
};

export type KeyDef = {
  en: string;
  shift?: string;
  finger: Finger;
  width?: number;
};

export const englishKeyboardRows: KeyDef[][] = [
  [
    { en: "`", shift: "~", finger: "l-pinky" },
    { en: "1", shift: "!", finger: "l-pinky" },
    { en: "2", shift: "@", finger: "l-ring" },
    { en: "3", shift: "#", finger: "l-middle" },
    { en: "4", shift: "$", finger: "l-index" },
    { en: "5", shift: "%", finger: "l-index" },
    { en: "6", shift: "^", finger: "r-index" },
    { en: "7", shift: "&", finger: "r-index" },
    { en: "8", shift: "*", finger: "r-middle" },
    { en: "9", shift: "(", finger: "r-ring" },
    { en: "0", shift: ")", finger: "r-pinky" },
    { en: "-", shift: "_", finger: "r-pinky" },
    { en: "=", shift: "+", finger: "r-pinky" },
    { en: "⌫", finger: "r-pinky", width: 2 },
  ],
  [
    { en: "Tab", finger: "l-pinky", width: 1.6 },
    { en: "q", shift: "Q", finger: "l-pinky" },
    { en: "w", shift: "W", finger: "l-ring" },
    { en: "e", shift: "E", finger: "l-middle" },
    { en: "r", shift: "R", finger: "l-index" },
    { en: "t", shift: "T", finger: "l-index" },
    { en: "y", shift: "Y", finger: "r-index" },
    { en: "u", shift: "U", finger: "r-index" },
    { en: "i", shift: "I", finger: "r-middle" },
    { en: "o", shift: "O", finger: "r-ring" },
    { en: "p", shift: "P", finger: "r-pinky" },
    { en: "[", shift: "{", finger: "r-pinky" },
    { en: "]", shift: "}", finger: "r-pinky" },
    { en: "\\", shift: "|", finger: "r-pinky", width: 1.4 },
  ],
  [
    { en: "Caps", finger: "l-pinky", width: 1.9 },
    { en: "a", shift: "A", finger: "l-pinky" },
    { en: "s", shift: "S", finger: "l-ring" },
    { en: "d", shift: "D", finger: "l-middle" },
    { en: "f", shift: "F", finger: "l-index" },
    { en: "g", shift: "G", finger: "l-index" },
    { en: "h", shift: "H", finger: "r-index" },
    { en: "j", shift: "J", finger: "r-index" },
    { en: "k", shift: "K", finger: "r-middle" },
    { en: "l", shift: "L", finger: "r-ring" },
    { en: ";", shift: ":", finger: "r-pinky" },
    { en: "'", shift: '"', finger: "r-pinky" },
    { en: "Enter", finger: "r-pinky", width: 2.1 },
  ],
  [
    { en: "Shift", finger: "l-pinky", width: 2.4 },
    { en: "z", shift: "Z", finger: "l-pinky" },
    { en: "x", shift: "X", finger: "l-ring" },
    { en: "c", shift: "C", finger: "l-middle" },
    { en: "v", shift: "V", finger: "l-index" },
    { en: "b", shift: "B", finger: "l-index" },
    { en: "n", shift: "N", finger: "r-index" },
    { en: "m", shift: "M", finger: "r-index" },
    { en: ",", shift: "<", finger: "r-middle" },
    { en: ".", shift: ">", finger: "r-ring" },
    { en: "/", shift: "?", finger: "r-pinky" },
    { en: "Shift", finger: "r-pinky", width: 2.4 },
  ],
  [{ en: "Space", finger: "thumb", width: 6 }],
];

const englishCharIndex: Record<
  string,
  { key: KeyDef; shift: boolean; rowIndex: number; colIndex: number }
> = {};
englishKeyboardRows.forEach((row, ri) => {
  row.forEach((key, ci) => {
    englishCharIndex[key.en] = { key, shift: false, rowIndex: ri, colIndex: ci };
    if (key.shift) {
      englishCharIndex[key.shift] = { key, shift: true, rowIndex: ri, colIndex: ci };
    }
  });
});

export function englishLookupChar(ch: string) {
  return englishCharIndex[ch];
}

export type Lesson = {
  slug: string;
  title: string;
  englishTitle: string;
  description: string;
  level: "Beginner" | "Intermediate" | "Advanced";
  keys: string;
  minutes: number;
  text: string;
};

export const englishLessons: Lesson[] = [
  // Home Row
  {
    slug: "eng-ch1",
    title: "Lesson 1",
    englishTitle: "Home Row: f j",
    description: "Home Row",
    level: "Beginner",
    keys: "f j",
    minutes: 3,
    text: "fjfj fjfj ffjj fjjf ffjj fjjf fjfj fjfj fjfj fjfj ffjj fjjf",
  },
  {
    slug: "eng-ch2",
    title: "Lesson 2",
    englishTitle: "Home Row: d k",
    description: "Home Row",
    level: "Beginner",
    keys: "d k",
    minutes: 3,
    text: "dkdk dkdk ddkk dkkd ddkk dkkd dkdk dkdk dkdk dkdk ddkk dkkd",
  },
  {
    slug: "eng-ch3",
    title: "Lesson 3",
    englishTitle: "Home Row: s l",
    description: "Home Row",
    level: "Beginner",
    keys: "s l",
    minutes: 3,
    text: "slsl slsl ssll slls ssll slls slsl slsl slsl slsl ssll slls",
  },
  {
    slug: "eng-ch4",
    title: "Lesson 4",
    englishTitle: "Home Row: a ;",
    description: "Home Row",
    level: "Beginner",
    keys: "a ;",
    minutes: 3,
    text: "a;a; a;a; aa;; a;;a aa;; a;;a a;a; a;a; a;a; a;a; aa;; a;;a",
  },
  {
    slug: "eng-ch5",
    title: "Lesson 5",
    englishTitle: "Home Row: a s d f",
    description: "Home Row",
    level: "Beginner",
    keys: "a s d f",
    minutes: 3,
    text: "asdf asdf asdf asdf fdsa fdsa fdsa fdsa afsd afsd afsd afsd",
  },
  {
    slug: "eng-ch6",
    title: "Lesson 6",
    englishTitle: "Home Row: j k l ;",
    description: "Home Row",
    level: "Beginner",
    keys: "j k l ;",
    minutes: 3,
    text: "jkl; jkl; jkl; jkl; ;lkj ;lkj ;lkj ;lkj j;kl j;kl j;kl j;kl",
  },
  {
    slug: "eng-ch7",
    title: "Lesson 7",
    englishTitle: "Home Row: g h",
    description: "Home Row",
    level: "Beginner",
    keys: "g h",
    minutes: 3,
    text: "ghgh ghgh gghh ghhg gghh ghhg fghj fghj ghgh ghgg hhgh hggh",
  },
  {
    slug: "eng-ch8",
    title: "Lesson 8",
    englishTitle: "Home Row: a s d f g",
    description: "Home Row",
    level: "Beginner",
    keys: "L-5 + G",
    minutes: 3,
    text: "asdfg asdfg asdfg",
  },
  {
    slug: "eng-ch9",
    title: "Lesson 9",
    englishTitle: "Home Row: j k l ; h",
    description: "Home Row",
    level: "Beginner",
    keys: "L-6 + H",
    minutes: 3,
    text: "jkl;h jkl;h jkl;h",
  },
  {
    slug: "eng-ch10",
    title: "Lesson 10",
    englishTitle: "Home Row Words",
    description: "Home Row",
    level: "Intermediate",
    keys: "Home Row Words",
    minutes: 3,
    text: "sad fad lad dad lass fall glass flak flask alas alas add all ask ash dash flash slash gash hash jag lag sag flag",
  },
  {
    slug: "eng-ch11",
    title: "Lesson 11",
    englishTitle: "Home Row: All Keys",
    description: "Home Row",
    level: "Intermediate",
    keys: "ALL HOME ROW",
    minutes: 3,
    text: "ask dad all salads fall; lass as ads add salsa jaff kad; flask sad alfa jak kaj",
  },
  // Top Row
  {
    slug: "eng-ch12",
    title: "Lesson 12",
    englishTitle: "Top Row: r u",
    description: "Top Row",
    level: "Beginner",
    keys: "r u",
    minutes: 2,
    text: "ruru ruru rruu ruur rruu ruur frju frju ruru ruru rruu ruur",
  },
  {
    slug: "eng-ch13",
    title: "Lesson 13",
    englishTitle: "Top Row: e i",
    description: "Top Row",
    level: "Beginner",
    keys: "e i",
    minutes: 2,
    text: "eiei eiei eeii eiie eeii eiie deki deki eiei eiei eeii eiie",
  },
  {
    slug: "eng-ch14",
    title: "Lesson 14",
    englishTitle: "Top Row: w o",
    description: "Top Row",
    level: "Beginner",
    keys: "w o",
    minutes: 2,
    text: "wowo wowo wwoo woow wwoo woow swlo swlo wowo wowo wwoo woow",
  },
  {
    slug: "eng-ch15",
    title: "Lesson 15",
    englishTitle: "Top Row: q p",
    description: "Top Row",
    level: "Beginner",
    keys: "q p",
    minutes: 2,
    text: "qpqp qpqp qqpp qppq qqpp qppq aq;p aq;p qpqp qpqp qqpp qppq",
  },
  {
    slug: "eng-ch16",
    title: "Lesson 16",
    englishTitle: "Top Row: q w e r",
    description: "Top Row",
    level: "Beginner",
    keys: "q w e r",
    minutes: 3,
    text: "qwer qwer qwer qwer rqew rqew rqew rqew wreq wreq wreq wreq",
  },
  {
    slug: "eng-ch17",
    title: "Lesson 17",
    englishTitle: "Top Row: u i o p",
    description: "Top Row",
    level: "Beginner",
    keys: "u i o p",
    minutes: 3,
    text: "uiop uiop uiop uiop puio puio puio puio iopu iopu iopu iopu",
  },
  {
    slug: "eng-ch18",
    title: "Lesson 18",
    englishTitle: "Top Row: t y",
    description: "Top Row",
    level: "Beginner",
    keys: "t y",
    minutes: 3,
    text: "tyty tyty ttyy tyyt ttyy tyyt ftjy ftjy tyty tytt yyty ytty",
  },
  {
    slug: "eng-ch19",
    title: "Lesson 19",
    englishTitle: "Top Row: q w e r t",
    description: "Top Row",
    level: "Beginner",
    keys: "L-16 + T",
    minutes: 3,
    text: "qwert qwert qwert",
  },
  {
    slug: "eng-ch20",
    title: "Lesson 20",
    englishTitle: "Top Row: u i o p y",
    description: "Top Row",
    level: "Beginner",
    keys: "L-17 + Y",
    minutes: 3,
    text: "uiopy uiopy uiopy",
  },
  {
    slug: "eng-ch21",
    title: "Lesson 21",
    englishTitle: "Top Row: q w e r t y u i o p",
    description: "Top Row",
    level: "Intermediate",
    keys: "TOP ROW WORDS",
    minutes: 3,
    text: "qwertyuiop qwertyuiop qwertyuiop",
  },
  {
    slug: "eng-ch22",
    title: "Lesson 22",
    englishTitle: "Top Row: All Keys",
    description: "Top Row",
    level: "Intermediate",
    keys: "ALL TOP ROW",
    minutes: 3,
    text: "top pot toy quit rope pure pour type put out our wire quiet power route true",
  },
  {
    slug: "eng-ch23",
    title: "Lesson 23",
    englishTitle: "Drill: L-10, 12 & 13",
    description: "Top Row",
    level: "Intermediate",
    keys: "DRILL",
    minutes: 3,
    text: "add your specific words here",
  },
  {
    slug: "eng-ch24",
    title: "Lesson 24",
    englishTitle: "Drill: L-14, 15 & 23",
    description: "Top Row",
    level: "Intermediate",
    keys: "DRILL",
    minutes: 3,
    text: "add your specific words here",
  },
  {
    slug: "eng-ch25",
    title: "Lesson 25",
    englishTitle: "Drill: L-10 & 21 (Home + Top)",
    description: "Top Row",
    level: "Intermediate",
    keys: "DRILL",
    minutes: 3,
    text: "add home top row mixed words here",
  },
  // Bottom Row
  {
    slug: "eng-ch26",
    title: "Lesson 26",
    englishTitle: "Bottom Row: v m",
    description: "Bottom Row",
    level: "Beginner",
    keys: "v m",
    minutes: 2,
    text: "vmvm vmvm vvmm vmmv vvmm vmmv fvjm fvjm vmvm vmvm vvmm vmmv",
  },
  {
    slug: "eng-ch27",
    title: "Lesson 27",
    englishTitle: "Bottom Row: c ,",
    description: "Bottom Row",
    level: "Beginner",
    keys: "c ,",
    minutes: 2,
    text: "c,c, c,c, cc,, c,,c cc,, c,,c dck, dck, c,c, c,c, cc,, c,,c",
  },
  {
    slug: "eng-ch28",
    title: "Lesson 28",
    englishTitle: "Bottom Row: x .",
    description: "Bottom Row",
    level: "Beginner",
    keys: "x .",
    minutes: 2,
    text: "x.x. x.x. xx.. x..x xx.. x..x sxl. sxl. x.x. x.x. xx.. x..x",
  },
  {
    slug: "eng-ch29",
    title: "Lesson 29",
    englishTitle: "Bottom Row: z /",
    description: "Bottom Row",
    level: "Beginner",
    keys: "z /",
    minutes: 2,
    text: "z/z/ z/z/ zz// z//z zz// z//z az;/ az;/ z/z/ z/z/ zz// z//z",
  },
  {
    slug: "eng-ch30",
    title: "Lesson 30",
    englishTitle: "Bottom Row: z x c v",
    description: "Bottom Row",
    level: "Beginner",
    keys: "z x c v",
    minutes: 3,
    text: "zxcv zxcv zxcv zxcv vzcx vzcx vzcx vzcx cxvz cxvz cxvz cxvz",
  },
  {
    slug: "eng-ch31",
    title: "Lesson 31",
    englishTitle: "Bottom Row: m , . /",
    description: "Bottom Row",
    level: "Beginner",
    keys: "m , . /",
    minutes: 3,
    text: "m,./ m,./ m,./ m,./ /,m. /,m. /,m. /,m. .,/m .,/m .,/m .,/m",
  },
  {
    slug: "eng-ch32",
    title: "Lesson 32",
    englishTitle: "Bottom Row: b n",
    description: "Bottom Row",
    level: "Beginner",
    keys: "b n",
    minutes: 3,
    text: "bnbn bnbn bbnn bnnb bbnn bnnb fbjn fbjn bnbn bnbb nnbn nbbn",
  },
  {
    slug: "eng-ch33",
    title: "Lesson 33",
    englishTitle: "Bottom Row: z x c v b",
    description: "Bottom Row",
    level: "Beginner",
    keys: "L-30 + B",
    minutes: 3,
    text: "zxcvb zxcvb zxcvb zxcvb",
  },
  {
    slug: "eng-ch34",
    title: "Lesson 34",
    englishTitle: "Bottom Row: n m , . /",
    description: "Bottom Row",
    level: "Beginner",
    keys: "L-31 + N",
    minutes: 3,
    text: "nm,./ nm,./ nm,./ nm,./",
  },
  {
    slug: "eng-ch35",
    title: "Lesson 35",
    englishTitle: "Bottom Row: All Keys Mixed",
    description: "Bottom Row",
    level: "Intermediate",
    keys: "BOTTOM ROW WORDS",
    minutes: 3,
    text: "zxcvbnm,./ zxcvbnm,./",
  },
  {
    slug: "eng-ch36",
    title: "Lesson 36",
    englishTitle: "Bottom Row: Real Words",
    description: "Bottom Row",
    level: "Intermediate",
    keys: "ALL BOTTOM ROW",
    minutes: 3,
    text: "zebra xray cave vocal bacon navy maze comma zombie exam civil zero pizza max next",
  },
  {
    slug: "eng-ch37",
    title: "Lesson 37",
    englishTitle: "Drill: L-25 & 26",
    description: "Bottom Row",
    level: "Intermediate",
    keys: "DRILL",
    minutes: 3,
    text: "add your lesson specific words here",
  },
  {
    slug: "eng-ch38",
    title: "Lesson 38",
    englishTitle: "Drill: L-32 & 37",
    description: "Bottom Row",
    level: "Intermediate",
    keys: "DRILL",
    minutes: 3,
    text: "add your lesson specific words here",
  },
  {
    slug: "eng-ch39",
    title: "Lesson 39",
    englishTitle: "Drill: L-21 & 35",
    description: "Bottom Row",
    level: "Intermediate",
    keys: "DRILL",
    minutes: 3,
    text: "add your lesson specific words here",
  },
  // Shift Key
  {
    slug: "eng-ch40",
    title: "Lesson 40",
    englishTitle: "Shift: Home Row Keys",
    description: "Shift Key",
    level: "Intermediate",
    keys: "SHIFT + HOME",
    minutes: 3,
    text: "aA sS dD fF gG hH jJ kK lL ;:",
  },
  {
    slug: "eng-ch41",
    title: "Lesson 41",
    englishTitle: "Shift: First Letter Capital",
    description: "Shift Key",
    level: "Intermediate",
    keys: "CAPITAL WORDS",
    minutes: 3,
    text: "Patna Megamind Delhi Monday March Apple India Rohan Ganga Mango",
  },
  {
    slug: "eng-ch42",
    title: "Lesson 42",
    englishTitle: "Shift: Top Row Keys",
    description: "Shift Key",
    level: "Intermediate",
    keys: "SHIFT + TOP",
    minutes: 3,
    text: "qQ wW eE rR tT yY uU iI oO pP",
  },
  {
    slug: "eng-ch43",
    title: "Lesson 43",
    englishTitle: "Shift: Top Row Words",
    description: "Shift Key",
    level: "Intermediate",
    keys: "CAPITAL WORDS",
    minutes: 3,
    text: "Delhi Ganga Rohan Apple Sunday Friday August",
  },
  {
    slug: "eng-ch44",
    title: "Lesson 44",
    englishTitle: "Shift: Bottom Row Keys",
    description: "Shift Key",
    level: "Intermediate",
    keys: "SHIFT + BOTTOM",
    minutes: 3,
    text: "zZ xX cC vV bB nN mM ,.",
  },
  {
    slug: "eng-ch45",
    title: "Lesson 45",
    englishTitle: "Shift: All Rows Mixed",
    description: "Shift Key",
    level: "Intermediate",
    keys: "CAPITAL WORDS",
    minutes: 3,
    text: "Zebra Varanasi Nagpur Mumbai Chennai Bihar Zero Victor",
  },
  // Paragraphs
  {
    slug: "eng-ch46",
    title: "Lesson 46",
    englishTitle: "Story: Home + Top",
    description: "Paragraphs",
    level: "Intermediate",
    keys: "PARAGRAPH 1",
    minutes: 3,
    text: "He is a dad. He has a red hat and a big coat. She sat there with him on the green grass. The cat is there too, looking at the birds. She fed the cat a fresh fish. He got a big red cap from the shop. We sat on the mat and ate a sweet plum together. It was a fine day to rest and read a nice book in the shade of the tall tree.",
  },
  {
    slug: "eng-ch47",
    title: "Lesson 47",
    englishTitle: "Story: Home + Bottom",
    description: "Paragraphs",
    level: "Intermediate",
    keys: "PARAGRAPH 2",
    minutes: 3,
    text: "A man has a van parked near the lane. Mac can nab a cab to go to the shop fast. Dan had a bad jam on the main road today. Max is a mad man with a heavy bag of cans. A cat ran from the van to the bus stop. We can cab it to the dock and catch a boat. Bad gas can cause a van to stop dead on a trip.",
  },
  {
    slug: "eng-ch48",
    title: "Lesson 48",
    englishTitle: "Story: The Clever Fox",
    description: "Paragraphs",
    level: "Advanced",
    keys: "STORY MODE",
    minutes: 5,
    text: "Once upon a time, in a small green village, there lived a clever fox. Why was he so clever? He always thought carefully before acting on any plan. One day, he found a shiny, golden coin near the dark river bank. He stopped and asked himself, who dropped this here? He looked around, but nobody was there at all. So, he smiled and walked away quietly to his hidden den. Later that night, he shared a great meal with his friends under the bright moon.",
  },
  // Number Row
  {
    slug: "eng-ch49",
    title: "Lesson 49",
    englishTitle: "Number Row: 1 to 5",
    description: "Number Row",
    level: "Intermediate",
    keys: "NUMBERS: LEFT",
    minutes: 3,
    text: "1 2 3 4 5",
  },
  {
    slug: "eng-ch50",
    title: "Lesson 50",
    englishTitle: "Number Row: 6 to 0",
    description: "Number Row",
    level: "Intermediate",
    keys: "NUMBERS: RIGHT",
    minutes: 3,
    text: "6 7 8 9 0",
  },
  {
    slug: "eng-ch51",
    title: "Lesson 51",
    englishTitle: "Number Row: Complete Drill",
    description: "Number Row",
    level: "Intermediate",
    keys: "NUMBERS: ALL",
    minutes: 3,
    text: "1 2 3 4 5 6 7 8 9 0",
  },
  {
    slug: "eng-ch52",
    title: "Lesson 52",
    englishTitle: "Number Shift & Basic Symbols - Extended",
    description: "Full Keyboard Master",
    level: "Advanced",
    keys: "ADVANCED",
    minutes: 3,
    text: "Press shift and one for exclamation mark! Press shift and two for at symbol @ and shift three for hash #. Use shift four for dollar sign $ and shift five for percent sign %. Always double check your symbols like @ and # while typing passwords or special codes to maintain high precision.",
  },
  {
    slug: "eng-ch53",
    title: "Lesson 53",
    englishTitle: "Advanced Shift Symbols - Extended",
    description: "Full Keyboard Master",
    level: "Advanced",
    keys: "ADVANCED",
    minutes: 5,
    text: "Continue learning upper row shifts including caret symbol ^, ampersand & sign, and multiplication asterisk *. Open parenthesis ( and close parenthesis ) require stretching your pinky fingers correctly. Practice these operators (&, *, ^) carefully to ensure smooth coding and technical documentation workflows.",
  },
  {
    slug: "eng-ch54",
    title: "Lesson 54",
    englishTitle: "Alpha-Numeric Mixed Drill - Extended",
    description: "Full Keyboard Master",
    level: "Advanced",
    keys: "ADVANCED",
    minutes: 5,
    text: "Order number four thousand two hundred fifty-five contains twelve hardware items ready for laboratory sector eight. Room number nine received four hundred fifty paper reams today morning. User twelve requires exactly ten new ethernet cables for testing batch number six without any further delay.",
  },
  {
    slug: "eng-ch55",
    title: "Lesson 55",
    englishTitle: "Symbols & Numbers Paragraph - Extended",
    description: "Full Keyboard Master",
    level: "Advanced",
    keys: "ADVANCED",
    minutes: 3,
    text: "Please transfer fifty percent of the total project amount ($500) into corporate account number #123 immediately! Verify whether item unit costs $10 or $20 before finalizing the requisition. The final financial breakdown is one hundred percent verified and approved for the upcoming fiscal quarter budget allocation.",
  },
  {
    slug: "eng-ch56",
    title: "Lesson 56",
    englishTitle: "Advanced Punctuation & Brackets - Extended",
    description: "Full Keyboard Master",
    level: "Advanced",
    keys: "ADVANCED",
    minutes: 3,
    text: "Call technical customer support at (555) 123-4567 directly and check the bulk discount rate (*10 items per box). The primary calculation formula is written as (A & B) multiplied by C equals 50. Always keep security code number (99) confidential and safe at all times during administrative operations.",
  },
  {
    slug: "eng-ch57",
    title: "Lesson 57",
    englishTitle: "Full Keyboard Practice - Extended",
    description: "Full Keyboard Master",
    level: "Advanced",
    keys: "ADVANCED",
    minutes: 5,
    text: "Welcome to the central technology laboratory facility! We manage twelve high-speed workstations, four network printers, and four hundred fifty paper reams to support our monthly operating budget of five hundred dollars. Room number nine is fully open for test number one under batch two guidelines. Please verify all ten connected systems, check power configurations, and ensure network stability before closing time arrives at five PM sharp. Consistency and accuracy remain the most critical factors for every active participant aiming to build reliable muscle memory across standard alphanumeric and symbol keys.",
  },
  {
    slug: "eng-ch58",
    title: "Lesson 58",
    englishTitle: "Technical Logistics - Extended",
    description: "Full Keyboard Master",
    level: "Advanced",
    keys: "ADVANCED",
    minutes: 5,
    text: "Equipment maintenance requires careful handling of internal power supply units, pure sine wave backup inverters, and high-efficiency cooling fans to protect sensitive hardware components. Ensure that voltage stability remains strictly between two hundred twenty volts and two hundred forty volts during peak operational hours to prevent unexpected hardware reboot cycles or sudden data corruption. Routine diagnostic checks help identify failing storage drives, faulty USB connections, and peripheral device anomalies before they disrupt daily administrative tasks or scheduled training sessions.",
  },
  {
    slug: "eng-ch59",
    title: "Lesson 59",
    englishTitle: "Endurance Test - Extended",
    description: "Full Keyboard Master",
    level: "Advanced",
    keys: "ADVANCED",
    minutes: 5,
    text: "Professional touch typing requires maintaining an even rhythm, correct home row finger placement, and minimizing unnecessary wrist movement during long stretches of continuous text generation. As speed increases progressively toward thirty words per minute and beyond, focus must shift entirely toward precision, spelling accuracy, and fluid key actuation across numbers, shift symbols, and punctuation marks alike. Developing this natural cadence takes disciplined practice, patience, and regular sessions focusing on problematic character combinations without looking down at the keyboard layout.",
  },
  {
    slug: "eng-ch60",
    title: "Lesson 60",
    englishTitle: "Ultimate Challenge - Extended",
    description: "Full Keyboard Master",
    level: "Advanced",
    keys: "ADVANCED",
    minutes: 5,
    text: "The final certification test for laboratory sector eight officially commences at exactly ten o'clock in the morning! Bring your verified identification card marked with code number four thousand two hundred fifty-five, check your assigned workstation ranging from one to twelve, and log into the portal securely. Over ninety percent of active participants successfully cleared the thirty words per minute threshold during preliminary evaluations with exceptional precision scores. Good luck to every single candidate as you complete this ultimate keyboard mastery module today!",
  },
];

export const englishCurriculumBase = [
  {
    category: "Home Row",
    slug: "eng-home-row-category",
    title: "Home Row",
    englishTitle: "Home Row",
    description: "Learn the middle row of the keyboard.",
    isCategory: true,
  },
  ...englishLessons
    .filter((l) => l.description === "Home Row")
    .map((l) => ({ ...l, category: "Home Row", isCategory: false })),
  {
    category: "Top Row",
    slug: "eng-top-row-category",
    title: "Top Row",
    englishTitle: "Top Row",
    description: "Learn the top row of the keyboard.",
    isCategory: true,
  },
  ...englishLessons
    .filter((l) => l.description === "Top Row")
    .map((l) => ({ ...l, category: "Top Row", isCategory: false })),
  {
    category: "Bottom Row",
    slug: "eng-bottom-row-category",
    title: "Bottom Row",
    englishTitle: "Bottom Row",
    description: "Learn the bottom row of the keyboard.",
    isCategory: true,
  },
  ...englishLessons
    .filter((l) => l.description === "Bottom Row")
    .map((l) => ({ ...l, category: "Bottom Row", isCategory: false })),
  {
    category: "Shift Key",
    slug: "eng-shift-key-category",
    title: "Shift Key",
    englishTitle: "Shift Key",
    description: "Learn how to use the shift key.",
    isCategory: true,
  },
  ...englishLessons
    .filter((l) => l.description === "Shift Key")
    .map((l) => ({ ...l, category: "Shift Key", isCategory: false })),
  {
    category: "Paragraphs",
    slug: "eng-paragraphs-category",
    title: "Paragraphs",
    englishTitle: "Paragraphs",
    description: "Practice typing sentences and stories.",
    isCategory: true,
  },
  ...englishLessons
    .filter((l) => l.description === "Paragraphs")
    .map((l) => ({ ...l, category: "Paragraphs", isCategory: false })),
  {
    category: "Number Row",
    slug: "eng-number-row-category",
    title: "Number Row",
    englishTitle: "Number Row",
    description: "Practice the number row and symbols.",
    isCategory: true,
  },
  ...englishLessons
    .filter((l) => l.description === "Number Row")
    .map((l) => ({ ...l, category: "Number Row", isCategory: false })),
  {
    category: "Full Keyboard Master",
    slug: "eng-full-keyboard-master-category",
    title: "Full Keyboard Master",
    englishTitle: "Full Keyboard Master",
    description: "Advanced practice with symbols, numbers, and full keyboard.",
    isCategory: true,
  },
  ...englishLessons
    .filter((l) => l.description === "Full Keyboard Master")
    .map((l) => ({ ...l, category: "Full Keyboard Master", isCategory: false })),
];
