const map = {
  f: "ि",
  j: "र",
  d: "क",
  k: "ा",
  s: "े",
  l: "स",
  a: "ं",
  ";": "य",
  g: "ह",
  h: "ी",
  r: "त",
  u: "न",
  e: "म",
  i: "प",
  w: "ू",
  o: "व",
  q: "ु",
  p: "च",
  t: "ज",
  y: "ल",
  c: "ब",
  n: "द",
  x: "ग",
  m: "उ",
  v: "अ",
  z: "्र",
  ",": "ए",
  ".": "ण्",
  "/": "ध्",
  " ": " ",
};

const ch11Sequence = [
  "d",
  "j",
  "s",
  " ",
  "j",
  "k",
  "s",
  ";",
  "k",
  " ",
  "l",
  "k",
  "j",
  "s",
  " ",
  "f",
  "d",
  "j",
  "k",
  ";",
  "k",
  " ",
  "l",
  "g",
  " ",
  "l",
  "g",
  "k",
  "j",
  "k",
  " ",
  "f",
  "d",
  "j",
  "k",
  ";",
  "s",
  " ",
  "d",
  "k",
  "s",
  "l",
  "k",
  "s",
  "a",
  " ",
  "j",
  "g",
  "k",
  " ",
  "f",
  "l",
  ";",
  "k",
  "j",
  "k",
  "s",
  "a",
  " ",
  ";",
  "s",
  " ",
  "d",
  "k",
  "j",
  " ",
  "j",
  "g",
  " ",
  "l",
  "k",
  "g",
  " ",
  "d",
  "s",
  "l",
  "j",
  " ",
  "d",
  "h",
  " ",
  "j",
  "l",
  " ",
  "f",
  "d",
  "l",
  " ",
  "d",
  "j",
  "k",
  " ",
  "l",
  "g",
  "h",
  " ",
  "d",
  "k",
  "s",
  "l",
  " ",
  "j",
  "k",
  "s",
  " ",
  "l",
  "d",
  "s",
  "a",
  " ",
  "f",
  "d",
  ";",
  "s",
  " ",
  "g",
  "k",
  "a",
  " ",
  "d",
  "j",
  "s",
  "a",
  " ",
  "j",
  "k",
  "s",
  "d",
  " ",
  "l",
  "k",
  " ",
  "g",
  "h",
  " ",
  "l",
  "j",
  " ",
  "f",
  "d",
  ";",
  "k",
  " ",
  ";",
  "g",
  "h",
  "a",
  " ",
  "d",
  "g",
  "h",
  " ",
  "l",
  "d",
  "k",
  " ",
  "g",
  "k",
  "s",
  "a",
  " ",
  "l",
  "h",
  "l",
  "s",
  " ",
  "l",
  "k",
  "g",
  "l",
  " ",
  "f",
  "d",
  " ",
  "l",
  "k",
  "j",
  "h",
  " ",
  "d",
  "l",
  "s",
];
const ch22Str =
  "dke jke uke ty iou le; dgk fu;e firk pk; ikuh thou ekyk iwtk lqeu dey egy ued peu ikyd edku lkeku puk u;k pqi iqy ewy pwd lp ikl ltk jkr etk jkt dy gkj thr ihyk uhyk dkyk lhuk";
const ch23Str =
  "lhuk dkyk uhyk ihyk thr gkj dy jkt etk jkr ltk ikl lp pwd ewy iqy pqi u;k puk lkeku edku ikyd peu ued egy dey lqeu iwtk ekyk thou ikuh pk; firk fu;e dgk le; iou ty uke jke dke";
const ch24Str =
  "ty pqi ewy dke uhyk iou lqeu ikyd edku dgk jkt lp ikuh jke puk ekyk gkj dkyk iwtk u;k ued lkeku ltk ihyk jkr iqy peu lhuk firk dey egy fu;e pk; uke etk thr pwd le; ikl dy";

const chapters = [
  { cat: "Home Row", title: "Ch 1", sub: "ि र", keys: ["f", "j"] },
  { cat: "Home Row", title: "Ch 2", sub: "क ा", keys: ["d", "k"] },
  { cat: "Home Row", title: "Ch 3", sub: "े स", keys: ["s", "l"] },
  { cat: "Home Row", title: "Ch 4", sub: "ं य", keys: ["a", ";"] },
  { cat: "Home Row", title: "Ch 5", sub: "ं े क ि", keys: ["a", "s", "d", "f"] },
  { cat: "Home Row", title: "Ch 6", sub: "र ा स य", keys: ["j", "k", "l", ";"] },
  { cat: "Home Row", title: "Ch 7", sub: "ह ी", keys: ["g", "h"] },
  { cat: "Home Row", title: "Ch 8", sub: "ं े क ि ह", keys: ["a", "s", "d", "f", "g"] },
  { cat: "Home Row", title: "Ch 9", sub: "र ा स य ी", keys: ["j", "k", "l", ";", "h"] },
  {
    cat: "Home Row",
    title: "Ch 10",
    sub: "होम रो",
    keys: ["a", "s", "d", "f", "g", "h", "j", "k", "l", ";"],
  },
  { cat: "Home Row", title: "Ch 11", sub: "शब्द अभ्यास", special: ch11Sequence.join("") },
  { cat: "Top Row", title: "Ch 12", sub: "त न", keys: ["r", "u"] },
  { cat: "Top Row", title: "Ch 13", sub: "म प", keys: ["e", "i"] },
  { cat: "Top Row", title: "Ch 14", sub: "ू व", keys: ["w", "o"] },
  { cat: "Top Row", title: "Ch 15", sub: "ु च", keys: ["q", "p"] },
  { cat: "Top Row", title: "Ch 16", sub: "ु ू म त", keys: ["q", "w", "e", "r"] },
  { cat: "Top Row", title: "Ch 17", sub: "न प व च", keys: ["u", "i", "o", "p"] },
  { cat: "Top Row", title: "Ch 18", sub: "ज ल", keys: ["t", "y"] },
  { cat: "Top Row", title: "Ch 19", sub: "ु ू म त ज", keys: ["q", "w", "e", "r", "t"] },
  { cat: "Top Row", title: "Ch 20", sub: "ल न प व च", keys: ["y", "u", "i", "o", "p"] },
  {
    cat: "Top Row",
    title: "Ch 21",
    sub: "टॉप रो",
    keys: ["q", "w", "e", "r", "t", "y", "u", "i", "o", "p"],
  },
  { cat: "Mixed", title: "Ch 22", sub: "अभ्यास 1", special: ch22Str },
  { cat: "Mixed", title: "Ch 23", sub: "अभ्यास 2", special: ch23Str },
  { cat: "Mixed", title: "Ch 24", sub: "अभ्यास 3", special: ch24Str },
  { cat: "Bottom Row", title: "Ch 25", sub: "अ उ", keys: ["v", "m"] },
  { cat: "Bottom Row", title: "Ch 26", sub: "ब ए", keys: ["c", ","] },
  { cat: "Bottom Row", title: "Ch 27", sub: "ग ण्", keys: ["x", "."] },
  { cat: "Bottom Row", title: "Ch 28", sub: "्र ध्", keys: ["z", "/"] },
];

function gen(keys) {
  let arr = [];
  for (let i = 0; i < 5; i++) {
    let w = "";
    for (let j = 0; j < 4; j++) w += map[keys[Math.floor(Math.random() * keys.length)]];
    arr.push(w);
  }
  return arr.join(" ");
}

function mapStr(s) {
  return s
    .split("")
    .map((c) => map[c] || c)
    .join("");
}

let result = "export const lessons: Lesson[] = [\n";
chapters.forEach((ch, i) => {
  let text = ch.special ? mapStr(ch.special) : gen(ch.keys);
  result += `  { slug: 'ch${i + 1}', title: '${ch.title}', hindiTitle: '${ch.sub}', description: '${ch.cat}', level: 'शुरुआती', keys: '${ch.sub}', minutes: 3, text: '${text}' },\n`;
});
result += "];\n";

import fs from "fs";
fs.writeFileSync("generated_lessons.txt", result);
console.log("Done");
